USE casedb; /* UPDATED 2023-11-05 */

/* PROCEDURES */
DROP PROCEDURE IF EXISTS abortAllocation;
DROP PROCEDURE IF EXISTS startAllocation;
DROP PROCEDURE IF EXISTS resetAllocation;
DROP PROCEDURE IF EXISTS allocateSpace;
DROP PROCEDURE IF EXISTS prioritizeSubjects;
DROP PROCEDURE IF EXISTS setSuitableRooms;
DROP PROCEDURE IF EXISTS LogAllocation;
DROP PROCEDURE IF EXISTS copyAllocRound;
DROP PROCEDURE IF EXISTS test_copyAllocRound;

/* FUNCTIONS */
DROP FUNCTION IF EXISTS getMissingItemAmount;
