version: "3.8"
services:
  siba_be:
    build: .
    container_name: siba_be
    env_file: .env
    environment:
    - DB_HOST=host.docker.internal
    ports:
      - '${BE_SERVER_PORT}:${BE_SERVER_PORT}'
